package com.example.abhishek.farmer_companion;

import java.util.HashMap;

/**
 * Created by Abhishek on 28-11-2016.
 * Text to be shown goes here.
 * Use correct naming convention to position the text.
 * format (crop name)_(section number)_( index number )
 * section number and index number are 0-based indices.
 */

public class TextInfoClass {
    HashMap<String, String> textInfo;

    TextInfoClass() {
        textInfo = new HashMap<>();
        textInfo.put("wheat_0_0", "Wheat is a major cereal crop of Punjab.In 2013 - 14, It was grown on 35.12 lac hectares and has production of 176.2 lac tonnes and per hectare yield of 50 quintal. ");
        textInfo.put("wheat_0_1", "Rotations : RiceWheat. Cotton-Wheat, Maize-Wheat, Maize/Rice-Potato-Wneat");
        textInfo.put("wheat_0_2", "Climatic Requirements : Wheat needs cool climate during the early stage of its growth.Warm temperature at this stage is unfavourable to tillering and also promotes several diseases.Too much of rain during the season results in heavy incidence of rusts.");
        textInfo.put("wheat_0_3", "The type of soil and the way it can determined if it is alkaline.");
        textInfo.put("wheat_1_0", "Seed Varieties.");
        textInfo.put("wheat_1_1", " The Video (in Punjabi) provides the details of the importance of deciding a correct variety of wheat seeds.");
        textInfo.put("wheat_1_2", "");
        textInfo.put("wheat_1_3", "PBW 677 (2015) :  It is a dwarf variety with an average plant height of 107 cm. Its ears are medium dense and tapering in shape with white smooth glumes. It is resistant to Yellow and Brown Rust. Its grains are Medium Bold, Amber, hard and Lustrous. It matures in about 157 days. Its average yield is 22.4 quintals per acre.   HD 3086 (2014) :   It is a dwarf variety with an average plant height of 96 cm. Its ears are medium dense and tapering in shape and white smooth glumes. Its grains are amber, hard and medium bold.It is resistant to yellow and brown rust but susceptible to Karnal bunt and Ioose smut diseases.It matures in about 156 days. Its average grain yield is 23.0 quintals per acre.  WH 1105 (2014) : It is a dwarf variety with an average plant height of 97 cm. Its ears are medium dense and tapering in shape with white smooth glumes. Its grains are amber. hard and medium bold. It is resistant to yellow and brown rust diseases. It matures in about 157 days.Its average grain yield is 23.1 quintals per acre. This variety is suitable for growing under poplar plantation.");
        textInfo.put("wheat_1_4", "HD 2967:(2011) :It is a dwarf variety with an average plant height         of 101 cm.It has profuse tilleri g.The ears are medium dense and tapering in shape with        white glumes.Its grains are amber, medium bold, hard and roundish in shape.lt is        moderately resistant to yellow rust and resistant to brown rust diseases.It takes about 157        days to mature.Its average yield is 21.4 quintals per acre.PBW502(2004) :It is a dwarf        variety with an average plant height of 95 cm.It tillers profusely.The ears are dense        and tapering in shape.Its grains are bold, amber, hard and lustrous.It is susceptible to        new race of yellow rust and resistant to brown rust, less susceptible to Karnal bunt        and susceptible to loose smut diseases.It matures in about 150 days.Its average yield is        19.5 quintals per acre.PBW 621 (2011):It is a dwarf varietywith an average plant height of        100 cm.It has profuse tillering.The ears are medium dense and tapering in shape with        white glumes.Its grains are amber, medium bold and hard.It is moderately resistant to yellow        rust and resistant to brown rust and less susceptible to Karnal bunt and loose smut diseases.        It takes about 158 days to mature.Its average yield is 21.1 quintals per acre. ");
        textInfo.put("wheat_1_5", "DBW 17 (2008) :It is a double dwarf variety with an average        plant height of 87 cm.It has profuse tillering.Its ears are medium dense and tapering in        shape with white smooth glumes.Its grains are amber, hard and medium bold.It is        susceptible to new race of yellow rust, moderately resistant to brown rust and less        susceptible to Karnal bunt.It matures in about 155 days.Its‘average grain yield is 20.0        quintals per acre.PBW 550 (2007) :It is a double dwarf variety with average plant height of        86 cm.The ears are medium dense tapering in shape and fully bearded with white smooth        glumes.Its grains are bold, amber, hard and lustrous.It is resistant to        brown rust, moderately resistant to yellow rust and susceptible to Karnal bunt and        loose smut diseases.It matures in about 146 days.Its average yield is 20.8 quintals per        acre. (Please see Agronomic Practices section for sowing time and seed rate.)WHD 943 (2011) :        It is a dwarf variety of durum wheat (Wadanak) with an average plant height of 93        cm.It tillers profusely.Its leaves are dark green and ears are dense, fully awned, tapering        with white smooth glumes.Its grains are amber, hard, bold, uniform and lustrous with low        incidence of yellow berry.lt possesses desirable quality characteristics and suitability for        pasta making.It is resistant to yellow and brown rusts and less susceptible to leaf blight.        It possesses field resistance to Karnal bunt disease.It takes about 154 days to        mature.Its average yield is 19.8 quintals per acre. ");
        textInfo.put("wheat_2_0", "Preparatory tillage :For normal sowing of wheat after paddy and        other kharif crops prepare the field as in the following slides:        ");
        textInfo.put("wheat_2_1", "There are three way for preparatory tillage :After Paddy        After Other Crops Zero/Minimum Tillage ");
        textInfo.put("wheat_2_2", "After paddy :lf the field has enough soil moisture undertake        tillage straightway, otherwise apply pre sowing irrigation (rauni).Use disc harrow        once followed by planking.Give another cultivation / ploughing with a cultivator.If the        soil is heavy, give one more cultivation before planking the soiI.Tractor drawn        cultivator with pulverizing roller -cum - puddler can also be used for preparing the        dry seed bed.When the paddy is harvested with combine the left - over straw can be managed        using following techniques:        The left over straw can be cut by using stubble shaver and collected after 2 to 3        days(sun drying) by using straw baler.Straw baler collects the straw and compresses it        in the form of bales.The left over straw can also be chopped by using paddy straw        chopper cum spreader into small pieces and the chopped straw can be mixed into the soil        by other tillage operations without any adverse effect on yield of wheat.Mixing of        straw improves soil properties over a long period.Wheat can also be sown in the combine        harvested fields with \"Happy Seeder\" in the standing paddy stubbles. ");
        textInfo.put("wheat_2_3", "After rauni give two cultivations / ploughings to be followed by planking.Tractor drawn cultivator with the pulverizing roller - cum - puddler can also be used        for preparing the dry seedbed.");
        textInfo.put("wheat_2_4", "Wheat can be grown without any preparatory tillage if there is        no serious problem of weeds to interfere in sowing.In weed -infested fields, weeds can be        controlled by spraying half litre of Gramoxone(Paraquat) in 200 litres of water, before        sowing.Zero tillage /minimum tillage has many benefits such as saving in diesel        and time, less environmental pollution, saving in water during first irrigation, lower        weeds infestation particularly Phalaris minor no yellowing of leaves after        first irrigation, improved, input use efficiency and less lodging.These factors        contribute, towards increased productivity with reduced cost of production.Besides this        time saved helps in timely planting of wheat over large areas.Use tractor drawn zero -till        drill or strip - till - drill for sowing wheat in unprepared fields. ");
        textInfo.put("wheat_2_5", " The Video Showcasing Zero Tillage");
        textInfo.put("wheat_2_6", "");
        textInfo.put("wheat_2_7", "In termite infested soil, first treat the seed with 4ml Dursbanf RubanfDurmet 20 EC (chlorpyriphos) or 6 ml Regent 596 SC (fipronil) per kg seed. Dry the seed in shade.");
        textInfo.put("wheat_2_8", " Loose smut replaces grain heads with smut, or masses of spores which infect the open flowers of healthy plants and grow into the seed, without showing any symptoms until maturity.");
        textInfo.put("wheat_2_9", " Treat the seed of all varieties except that of WHD 943, PDW 291, PDW 233 and TL 2908 with Raxil 60 F5 @ 13ml per 40 kg seed (Dissolve 13 ml Raxil 60 F5 in 30 ml water and mix with 40 kg seed) or vitavax Power TSWS @ 20g per 40kg seed or Vitavax @ 80g per 40kg seed or Seedex 2DS @ 40g per 40 kg seed for the control of loose smut.");
        textInfo.put("wheat_2_10", "  Video Showcasing the importance of Seed Treatment");
        textInfo.put("wheat_2_11", " Treat the seed with Captan or Thiram @ 120g per 40 kg seed if the seed is infected with blacktip and head scab. If the seed has been treated with vitavax Power as mentioned above do not treat the seed with Captan.");
        textInfo.put("wheat_2_12", " Treatment should not be done earlier than one month of sowing as it affects seed germination. Seed treatment can be done effectively with the seed treating drum. Inoculate the seed with recommended biofertilizers after treating the seed with insecticide and fungicide.");
        textInfo.put("wheat_2_13", "  Video Showcasing the use of Seed Treating Drum");
        textInfo.put("wheat_2_14", " Sow wheat after a heavy presowing irrigation (10 cm) except when it follows rice.In case wheat sowing is likely to be delayed due to the late harvest of rice the pre-sowing irrigation for wheat can be given to standing rice 5-1 0 days (depending upon soil type) before its harvest except where the crop is to be harvested with combine.This practice advances the sowing of wheat by about a week. For efficient use of irrigation water, farmers are advised to make 8 plots (kiaras) per acre in heavy textured soils and 16 plots per acre in light textured soils.  The first irrigation should be relatively light and given after threeweeks to October-sown crop and after four weeks to the crop sown Iater.The subsequent irrigations are also determined by the date of sowing.  Dates Of Sowing 		II		III		IV 				Weeks after the previous Irrigation Upto November 20		5-6		5-6		4 Nov 21 - Dec 20			5-6		3-4		2 December 21 - Jan 15		4		3		2");
        textInfo.put("wheat_3_0", " In the absence of a soil test, add the following amounts of fertilizers to wheat grown on medium fertility soils: Nutrients (Kg/Acre) : N : 50 Kg/Acre P2O5 : 25 Kg/Acre K2O : 12 Kg/Acre  Fertilizers (Kg/Acre) Urea : 110 KG/Acre DAP :  55  KG/Acre Or SuperPhosphate : 155 KG/Acre Or NitroPhosphate : 125 KG/Acre Muriate of Potash : 20KG/Acre ");
        textInfo.put("wheat_3_1", " If nitrogen is to be applied in the form of urea, apply half of the dose just before pre-sowing irrigation (rauni) or with the final preparatory tillage, the second dose within T days before or upto 5 days after first irrigation.   If Not Using Urea for Nitrogen : Drill ½ dose of N and whole of P and K at sowing and broadcast the remaining N with the first irrigation.   In light soils,apply ½  nitrogen at the time of sowing ¼  nitrogen immediately after first irrigation and the remaining ¼ nitrogen after second irrigation.  Drill 55 kg di-ammonium phosphate (DAP) per acre at sowing in medium fertility soils. Do not apply urea at sowing.  Apply 40 kg urea per acre for timely sown and 25 kg urea per acre for late sown (after mid December) wheat with first irrigation.");
        textInfo.put("wheat_3_2", "");
        textInfo.put("wheat_3_3", " Match leaf colour of the top most fully exposed intact leaf from the randomly selected ten plants with LCC under shade of your body before second irrigation (about 50-55 days after sowing).The leaves selected for matching colour with LCC should be free from disease/insect incidence and other nutrient deficiencies.");
        textInfo.put("wheat_3_4", "If leaf colour greenness of six or more out of ten leaves is less than shade 4 on LCC, top dress 40 kg urea per acre for timely sown and 25 kg urea per acre for late sown wheat with second irrigation. Otherwise, if leaf greenness is equal to or more than shade 4 on LCC top dress 25 kg urea per acre for timely sown and 15 kg urea per acre for late sown wheat with second irrigation.");
        textInfo.put("wheat_3_5", "The leaf colour chart can be purchased from the Department of Soil Science Punjab Agricultural University, Ludhiana.");
        textInfo.put("wheat_3_6", "Zinc deficiency generally appears in light soils under intensive cropping. If recommended dose of zinc sulphate has been applied to the kharif crop. Its application may be omitted to the following wheat crop. Paddy responds more to zinc application, therefore zinc should be applied to paddy and its residue is sufficient to meet the requirement of the following wheat crop. However, if zinc has not been applied to paddy and zinc deficiency is expected appears whose symptoms are a stunted and bushy crop with leaves chlorotic in the middle which later break and keep hanging.");
        textInfo.put("wheat_3_7", "What to Look For :  Paddock : Patchy growth, of stunted plants with short thin stems and usually pale green leaves. Heavily limed soils, sands and gravels or alkaline grey clays tend to be most affected. Zinc deficiency symptoms are usually seen on young seedlings early during the growing season.  Plant : Young to middle leaves develop yellow patches between the mid-vein and edge of the leaf and extend lengthways towards the tip and base of the leaf. This stripe may occur only on one side of the mid-vein.  The areas eventually die turning pale grey or brown  The leaf changes from green to a muddy greyish-green in the central areas of middle leaves.  Stunted plants often have 'diesel-soaked' leaves, showing dead areas about halfway along the leaves, causing them to bend and collapse in the middle section.  Maturity is delayed.");
        textInfo.put("wheat_3_8", "  Video Showcasing the Zinc Deficiency in Wheat.");
        textInfo.put("wheat_3_9", " Most sandy surfaced soils required copper and zinc treatments when initially cleared for agriculture.  Zinc is relatively immobile in soil and can become unavailable to crops in dry soil. Where soil levels are marginal, zinc deficiency can be induced by applications of lime, high nitrogen fertiliser, and copper fertiliser.  The use of root-pruning herbicides, particularly groups A and B can induce zinc deficiency.  Zinc deficiency is more common in high pH and clay soils.");
        textInfo.put("wheat_3_10", " Zinc deficiency can also be corrected by foliar spray of 0.5% zinc sulphate (21% Zinc).  Prepare the solution for spray by dissolving 1 kg zinc sulphate and 1/2 kg unslaked lime in 200 litres of water. This solution is sufficient for spraying an acre of wheat once. Two or three sprays at 15-day intervals are needed.  Application of 25 kg of zinc sulphate per acre which will be enough for 2-3 years.");
        textInfo.put("wheat_3_11", "  Manganese deficiency generally appears in light soils under intensive cropping especially in rice-wheat rotation.");
        textInfo.put("wheat_3_12", " Frequently plants are stunted and occur in distinct patches.  Initially, middle leaves are affected first, but it can be difficult to determine which leaves are most affected as symptoms rapidly spread to other leaves and the growing point. Leaves develop interveinal chlorosis and/ or white necrotic flecks and blotches. Leaves often kink, collapse and eventually die.  Tillering is reduced, with extensive leaf and tiller death. With extended deficiency, the plant may die.  Surviving plants produce fewer and smaller heads.");
        textInfo.put("wheat_3_13", " Manganese deficiency generally appears in light soils under intensive cropping especially in rice- wheat rotation and under dry conditions. ");
        textInfo.put("wheat_3_14", " In manganese deficient soils, give one spray of 0.5% manganese sulphate solution (1 kg manganese sulphate in 200 litres of water) 2-4 days before first irrigation and two to three sprays afterwards at weekly intervals on sunny days.  Do not grow varieties PDW 291, PDW 274 and PDW 233 in sandy soils as these varieties are prone to manganese deficiency.  Manganese sulphate should be sprayed only as its soil application is not profitable.");
        textInfo.put("wheat_3_15", "Wheat crop suffers from sulphur deficiency when sown in sandy soils.The deficiency is more severe when the winter rains continue for a long time in the early growth period.");
        textInfo.put("wheat_3_16", "The symptoms first appear on the younger leaves with fading of the normal green colour. This is followed in the veins.  The topmost leaves become light yellow except for the tip, while the lower leaves retain green colour for a longer time.  This is distinctly different from the nitrogen deficiency where the yellowing starts with the lower leaves. The plants are short in size with fewer tillers.");
        textInfo.put("wheat_3_17", " The deficiency is more severe when the winter rains continue for a long time in the early growth period.");
        textInfo.put("wheat_3_18", " Use sulphur-containing fertilizer as single super phosphate. Where phosphorus was not applied as single super phosphate, apply 100 kg of gypsum per acre before sowing to meet the sulphur requirement of the crop. Apply 20 to 40 kg Sulphur/ha.");
        textInfo.put("wheat_3_19", " Weeds can be controlled by two hand hoeings,one before first irrigation and second after first irrigation with wheel hoe kasola or khurpa etc. There are two methods of Weed Control :  1.) Cultural Control 2.) Chemical Control");
        textInfo.put("wheat_3_20", "");
        textInfo.put("wheat_3_21", " Sow quick growing wheat varieties from last week of October to first week of November in narrow rows at 15 cm spacing.  In fields having severe infestation of this weed, replace wheat with alternate crops like berseem, potato, raya, gobhi sarson and winter maize for 2 to 3 years.Preparation of soil mulch at sowing helps in eliminating the first flush of gulli danda.");
        textInfo.put("wheat_3_22", " Guili danda can be controlled with use of any of below listed herbicides:-  Pre-Emergence :  Pendimethalin 30 EC: 1.0 litre Within two days of sowing using 200 litres water. Trilluralin 48EC : 1.0 litre within two days of sowing using 200 litres water Post-Emergence (Before first irrigation) : 	Isoprotunon 75 WP : 300 gram in light textured, 400 gram in medium textures and 500 gram in heavy textured soil, Spray 2-3 days before first irrigation with 150 litres water.  Post Emergence (After first Irrigation) 	Isoproturo 75 WP : 500 grams in all types of soil. Spray 30-35 days after sowing with 150 litres water.");
        textInfo.put("wheat_3_23", " Control of HARD Broad Leaf Weeds :  Use Metsulfron 20WP (Algrip/Markgrip) in field 10g/acre in 100 litres of water, 30-35 days after sowing wheat crop.  Use Carfentrazone-Ethyl at 20g/acre in 200 litres of water and 30 days after sowing wheat crop, especially to control weeds like Button Booti.");
        textInfo.put("wheat_3_24", "  This is video in Punjabi talking about prevention of Weeds in Wheat Crops :");
        textInfo.put("wheat_4_0", " Harvesting and Threshing: Harvest and thresh wheat as soon as fully ripe to avoid grain shattering. The harvesting of wheat can be started five days earlier than dead ripe stage without adverse effect on the yield or quality of the grains.");
        textInfo.put("wheat_4_1", "Wheat can be harvested manually or by tractor-operated vertical conveyer reaper windrowers. For threshing, use power thresher with pro per safety devices to prevent accidents.For good performance operate these machines at cylinder speed recommended for wheat and also observe safety precautions against accidents.The syndicator type (Toka type) can be used to thresh the wheat crop with moisture content up to 20 percent. Combine harvesters can also be used for simultaneous harvesting and threshing of wheat. Delayed harvesting results in high grain losses. Stubbles can be bruised as fine wheat straw (turi) by using wheat-straw combine. ");
        textInfo.put("wheat_4_2", " Video of a Harvester");
        textInfo.put("wheat_4_3", " Video of a Combine");
        textInfo.put("wheat_4_4", " Video of Traditional Thresher : ");
        textInfo.put("wheat_5_0", "Pests.");
        textInfo.put("wheat_5_1", " Brown Wheat Mite  is a minor insect of wheat causing discolouration of leaves.");
        textInfo.put("wheat_5_2", "");
        textInfo.put("wheat_5_3", "");
        textInfo.put("wheat_5_4", "");
        textInfo.put("wheat_5_5", "");
        textInfo.put("wheat_5_6", "  Knapsack Sprayer");
        textInfo.put("wheat_5_7", "");
        textInfo.put("wheat_5_8", "");
        textInfo.put("wheat_5_9", "");
        textInfo.put("wheat_5_10", "  This video showcases the life cycle of aphids. ");
        textInfo.put("wheat_5_11", "");
        textInfo.put("wheat_5_12", "");
        textInfo.put("wheat_5_13", "  Lady Beetle Attacking the aphids");
        textInfo.put("wheat_5_14", "  Syphrid Larva attacking the Aphid. ");
        textInfo.put("wheat_5_15","");
        textInfo.put("wheat_5_18", "  Army Worm identification and life cycle.");
        textInfo.put("wheat_5_22", "  Army Worm Feeding On Wheat Crop Leaves : ");
        textInfo.put("wheat_5_24", " Army worm attacks wheat and barley during March-April. It dam ages leaves and earheads. Spray 200 ml Nuvan 85 SL (dichlorvos) or 400 ml Ekalux 25 EC (quinalphos) in 80-100 litres ofwater per acre with hand-operated knapsack sprayer or in 30 litres of water with a motorized knapsack sprayer. ");

        textInfo.put("wheat_0_0_pun", "ਕਣਕ ਪੰਜਾਬ ਵਿੱਚ ਅਂਲ਼ਾਜ ਦੀ ਮੁੱਖ ਫ਼ਸਲ ਹੈ ! ਇਸ ਦੀ ਕਾਸ਼ਤ ਸਾਲ 2013-14 ਵਿੱਚ 35.12 ਲੋਂਖ ਹੈੱਕਟੇਅਰ ਭੂਮੀ ਵਿੱਚ ਕੀਤੀ ਗਈ ਜਿਸ ਤੋੰ ਕੁਂਲ ਪੈਦਾਵਾਰ 176.2 ਲੋਂਖ ਟਨ ਹੋਈ ਅਤੇ ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 50.17 ਕੁਇੰਟਲ ਪੁਤੀ ਹੈਕਟੇਅਰ (20.07 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ) ਰਿਹਾ !");
        textInfo.put("wheat_0_1_pun", "ਜ਼ਮੀਨ  ਦੱਲਰ ਅਤੇ ਸੇਮ ਵਾਲੀਆਂ ਜ਼ਮੀਨਾਂ ਤੋਂ ਬਿਨਾਂ ਕਣਕ ਹਰ ਕਿਸਮ ਦੀ ਜ਼ਾਮੀਨ ਵਿੱਚ ਪੈਦਾ ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੇ ! ਚੰਗੇ ਜਲ-ਜ਼ਿਞਾਸ ਵਾਲੀ ਦਰਮਿਅਾਨੀ ਮੈਰਾ ਜ਼ਮੀਨ ਇਸ ਫ਼ਸਲ ਲਈ ਵਧੀਆ ਸਮਝੀ ਜਾਂਦੀ ਹੈ! ਵਡਾਣਕ ਕਣਕ  ਲਈ ਦਹਮਿਅਾਨੀ ਤੇਂ ਤਾਗ਼ੀ ਜ਼ਮੀਨ ਢੁਕਵੀਂ ਰੈ!ਫ਼ਸਲ ਚੱਕਰ  ਝੋਨਾ-ਕਣਕ, ਕਪਾਹ-ਕਣਕ, ਮੋਕੀ-ਕਣਕ, ਮੋਕੀ/ਝੋਨਾ-ਅਾਲੂ-ਕਣਕ, ਮੂੰਗੀ/ਅਰਹਰ/ਮਾਂਹ-ਕਣਕ!");
        textInfo.put("wheat_0_2_pun", "ਮੌਸਮ  ਸ਼ੁਰੂ ਵਿੱਚ ਕਣਕ ਨੁੂੰ ਠੰਢ ਦੀ ਲੋੜ ਹੁੰਦੀ ਹੈ ਅਤੇ ਇਸ ਸਮੇਂ ਜ਼ਿਅਾਦਾ ਤਘਮਾਨ ਪੌਦੇ ਦੇ ਜਾੜ ਮਾਰਨ ਲਈ ਅਂਨੁਕੂੂਲ ਨਗੀਂ ਹੁੰਦਾ ਅਡੇ ਇਸ ਨਾਲ ਕਈ ਬਿਮਾਚੀਆਂ ਵੀ ਬਹੁਤ ਫੈ਼ਲਦੀਆਂ ਹਨ ! ਬਹੁਤ ਮੀਂਹ ਪੈਣ ਨਾਲ ਕੁੰਗੀ ਦੇ ਫੈਲਣ ਦੀ ਸੰਭਾਵਨਾ ਵੀ ਵੱਧ ਜਾਂਦੀ ਹੈਂ!");
        textInfo.put("wheat_1_0_pun", "none");
        textInfo.put("wheat_1_1_pun", "ਵਿਡਿਓ (ਪੰਜਾਬੀ ਵਿੱਚ) ਕਣਕ ਦੇ ਸਹੀ ਕਿਸਮ ਦੇ ਬੀਜਾਂ ਨੂੰ ਚੁਣਨ ਦੇ ਮਹੱਤਵ ਦੇ ਵੇਰਵੇ ਮੁਹੱਈਆ ਕਰਦਾ ਹੈ.");
        textInfo.put("wheat_1_2_pun", "ਪੀ ਬੀ ਡਸ਼ਲਯੂ 677 (2015)  ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 107 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !  ਪਰ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 157 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 22.4 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !ਐਚ ਡੀ 3086(2015)   ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 96 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  !  ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ ! ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ | ਪਰ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 156 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 23.0 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !ਡਬਲਯੂ ਐਚ 1105 (2014) ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 97 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  !  ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ ! ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ | ਪਰ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 157 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 23.1 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ ! ਇਹ ਕਿਸਮ ਪਾਪਲ਼ਰ ਹੇਠ ਬੀਜਣ ਲਈ ਵੀ ਢੁੱਕਵੀਂ ਹੈ !");
        textInfo.put("wheat_1_3_pun", "ਐਚ ਡੀ 2967ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 101 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !  ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 157 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 21.4 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !ਪੀ ਬੀ ਡਸ਼ਲਯੂ  502 (2004) ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 95 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !   ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 150 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 19.5 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !ਪੀ ਬੀ ਡਸ਼ਲਯੂ 621 (2011) ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 100 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !   ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 158 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 21.2 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !");
        textInfo.put("wheat_1_4_pun", "ਡੀ ਬੀ ਡਸ਼ਲਯੂ 17 (2008)  ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 87 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !  ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 155 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 20.0 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !ਪੀ ਬੀ ਡਸ਼ਲਯੂ  550 (2007)  ਇਹ ਇੱਕ ਬੌਣੀ ਕਿਸਮ ਹੈੱ ਜਿਸ ਦਾ ਔਂਸਤ ਕੱਦ 86 ਸੈਂਟੀਮੀਟਰ ਹੈ ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !  ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 146 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 20.8 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !ਡਸ਼ਲਯੂ ਐਚ ਡੀ 943 (2011)  ਕਣਕ ਦੀ ਥੌਣੀ ਕਿਸਮ ਹੈ ਜਿਸ ਦਾ ਔਸਤ ਕੋਦ 93 ਸੈਟੀਠਿ ਹੈ! ਇਸ ਦੀਆਂ ਭਰਖੂਰ ਸ਼ਘਾਂ ਫੁੱਟਦੀਆਂ ਹਨ! ਸਿੱਟੇ ਹੁੰਦੇਹਨ, ਸੰਘਣੇ, ਕਸੀਰਾਂ, ਵਾਲੇ ਅਤੇ ਚਿੱਟੀਆਂ ਘੁੰਙੀਆਂ ਵਾਲੇ ਹੁੰਦੇ ਹਨ  ! ਦਾਣੇ ਦਰਮਿਅਾਨੇ ਮੋਟੇ , ਸ਼ਰਬਤੀ ਅਡੇ ਸਖ਼ਤ ਹੁੰਦੇ ਹਨ! ਇਹ ਕਿਸਮ ਪੀਲੀ ਅਤੇ ਭੂਰੀ ਕੁੰਗੀ ਦਾ ਟਾਕਰਾ ਕਰਨ ਦੀ ਸਮਰਬਾ ਰੱਖਦੀ ਹੈੱ !  ਪਰ ਕਰਨਾਲ ਬੰਟ ਤੇ ਕਾਂਰਿਆਰੀ ਇਸਨੁੂੰ ਲੱਗ ਸਕਦੀ ਹੈ! ਇਹ ਕਿਸਮ ਤਕਚੀਬਨ 154 ਦਿਨਾਂ ਵਿੱਚ ਪੱਕ ਜਾਂਦੀ ਹੈ ! ਇਸ ਦਾ ਔਂਸਤ ਝਾੜ 19.8 ਕੁਇੰਟਲ ਪੁਤੀ ਏਕੜ ਹੈ !");
        textInfo.put("wheat_2_0_pun", "ਕਾਸ਼ਤ ਦੇ ਉੱਨਤ ਢੰਗਖੇਤ ਦੀ ਤਿਅਾਰੀਂ  ਸਾਉਣੀ ਦੀਆਂ ਫ਼ਸਲਾਂ ਪਿੱਛੋਂ ਕਣਕ ਦੀ ਫ਼ਸਲ ਲਈ ਮੁੱਢਲੀ ਤਿਅਾਰੀ ਹੇਂਠਾਂ ਦਿਤੇ ਅਨੁਸਾਰ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ");
        textInfo.put("wheat_2_1_pun", "ਇਹ ਤਿੰਨ ਤਰੀਕਿਆਂ ਨਾਲ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ ਝੋਨੇ ਪਿੰਛੋਂਦੂਜੀਆਂ ਫ਼ਸਲਾਂ ਪਿੱਛੋਂਜ਼ੀਰੋ ਤਿਅਾਰੀਂ");
        textInfo.put("wheat_2_2_pun", "ਝੋਨੇ ਪਿੰਛੋਂ  ਜੇ ਗਿੱਲ ਕਾਫ਼ੀ ਹੋਵੇ ਤਾਂ ਥੇਤਾਂ ਦੀ ਵਹਾਢੀ ਸ਼ੁਰੂ ਕਰ ਦਿਓ , ਨਹੀਂ ਤਾਂ ਰੌਣੀ ਕਰੋ ! ਖੇਤਾਂ ਦੀ ਤਿਅਾਰੀ ਲਈ ਤਵੀਆਂ ਵਰਤੋ ਤੇ ਪਿੰਛੋਂ ਸੁਹਾਗਾ ਫੇਰੋ ! ਇਸ ਪਿੱਛੋਂ ਕਲਟੀਵੋਟਰ ਨਾਲ ਜ਼ਮੀਨ ਨੂੰ ਫਿਰ ਵਾਹੋ! ਜੇ ਜ਼ਮੀਨ ਭਾਰੀ ਹੋਵੇ ਤਾਂ ਸੱਹਾਗਾ ਮਾਰਨ ਤੋੰ ਪਹਿਲਾਂ ਇਂਕ ਵਾਰ ਫਿਰ ਵਾਹ ਲਓ! ਸੁੱਕੀ ਜ਼ਮੀਨ ਦੀ ਤਿਅਾਰੀ ਲਈ ਰੋਲਰ ਵਾਲੇ ਕਲਟੀਵੋਟਰ ਦੀ ਵਰਤੋ ਕਰੋ !ਜੇ ਝੋਨੇ ਦੀ ਕਟਾਈ ਕੰਬਾੲੀਨ ਨਾਲ ਕੀਤੀ ਹੋਵੇ ਤਾਂ ਬਚੀ ਹੌਈ ਪਰਾਲੀ ਨੁੂੰ ਹੇਠ ਲਿਖੇ ਤਰੀਕਿਆਂ ਦੁਅਾਰਾ ਸੰਭਾਲ ਸਕਦੇ ਹਾਂ  ਜੇ ਝੋਨੇ ਦੀ ਕਟਾਈ ਕੰਬਾੲੀਨ ਨਾਲ ਕੀਤੀ ਹੋਵੇ ਤਾਂ ਬਚੀ ਹੌਈ ਪਰਾਲੀ ਨੁੂੰ ਮਿੱਟੀ ਵਿਚ ਮਿਲਾ ਸਕਦੇ ਹਾਂ!");
        textInfo.put("wheat_2_3_pun", "ਦੂਜੀਆਂ ਫ਼ਸਲਾਂ ਪਿੱਛੋਂ  ਰੌਣੀ ਪਿੱਛੋਂ ਵੱਤਰ ਅਾਉਣ ਤੇ ਜ਼ਮੀਨ ਨੁੂੰ ਦੋ ਵਾਰ ਵਾਹੋ ਅਤੇ ਇਸ ਪਿੱਛੋਂ ਸੁਹਾਗਾ ਫੇਰੋ ! ਟਰੈਕਟਰ ਨਾਲ ਚੱਲਣ ਵਾਲਾ ਕਲਟੀਵੇਟਰ ਬਚੀਕ ਕਰਨ ਵਾਲਾ ਰੋਲਰ ਅਤੇ ੫ਡਲਰ ਵੀ ਜ਼ਮੀਨ ਦੀ ਤਿਅਾਰੀ ਲੲੀ ਵਰਤਿਅਾ ਜਾ ਸਕਦਾ ਹੈ!");
        textInfo.put("wheat_2_4_pun", "none");

    }

    String getText(String name) {
        String s = "";

        if (textInfo.containsKey(name))
            s = textInfo.get(name);
        else s = "Text is missing for this item";
        return s;
    }


}
